export enum EnumEventRole {
  INVITED = 'INPREPARATION',
  GROUPINVITED = 'SCHEDULED',
  GROUPSERIESINVITED = 'RUNNING',
  SERIESINVITED = 'ACCOMPLISHED',
  TUTORINVITED = 'CANCELLED',
  TUTORSERIESINVITED = 'TUTORSERIESINVITED',
  ATTENDEE = 'ATTENDEE',
  GROUPATTENDEE = 'GROUPATTENDEE',
  TUTOR = 'TUTOR',
  ORGANIZER = 'ORGANIZER'
}
